version: "3"
services:
  firefox:
    image: selenium/standalone-firefox:4.0.0-alpha-6-20200730
    volumes:
      - /dev/shm:/dev/shm
    hostname: 'firefox'

  python:
    build: .
    depends_on: 
      - firefox
    volumes: 
      - ./MydealzInput:/MydealzInput

      #docker-compose up --abort-on-container-exit